- hosts: localhost
  tasks:
    - import_role:
        name: peaceman.shared_hosting.common

    - import_role:
        name: peaceman.docker

    - import_role:
        name: peaceman.grosp.consul

    - import_role:
        name: peaceman.grosp.consul
        tasks_from: consul_service_definition.yml
      vars:
        name: edge-node
        template: edge-node-service.hcl.j2

    - import_role:
        name: peaceman.grosp.nss

    - import_role:
        name: peaceman.shared_hosting.server_nginx

    - import_role:
        name: peaceman.shared_hosting.app_system
      vars:
        username: proxycache

    - import_role:
        name: peaceman.shared_hosting.app_nginx
      vars:
        username: proxycache
        template: proxycache.conf.j2
        cert_groups:
          - name: "{{ hostname }}"
            domains:
              - "{{ hostname }}"
            tls:
              source: provided
              cert: "{{ lookup('file', proxy_cache_cert_file) }}"
              key: "{{ lookup('file', proxy_cache_cert_key_file) }}"

    - import_role:
        name: peaceman.elk
        tasks_from: journalbeat.yml
    - import_role:
        name: peaceman.elk
        tasks_from: filebeat.yml
    - import_role:
        name: peaceman.elk
        tasks_from: filebeat_nginx.yml

    - import_role:
        name: peaceman.grosp.node_exporter
