- hosts: localhost
  tasks:
    - import_role:
        name: peaceman.shared_hosting.common

    - import_role:
        name: peaceman.docker

    - import_role:
        name: peaceman.grosp.consul

    - import_role:
        name: peaceman.grosp.consul
        tasks_from: consul_service_definition.yml
      vars:
        name: edge-node
        template: edge-node-service.hcl.j2

    - import_role:
        name: peaceman.grosp.nss

    - name: Install proxycache
      import_tasks: proxycache.yml

    - import_role:
        name: peaceman.elk
        tasks_from: journalbeat.yml
    - import_role:
        name: peaceman.elk
        tasks_from: filebeat.yml
    - import_role:
        name: peaceman.elk
        tasks_from: filebeat_nginx.yml

    - import_role:
        name: peaceman.grosp.node_exporter
