x-restart-policy: &restart-policy
  restart: unless-stopped

version: "2.4"
services:
  nginx:
    image: peaceman/openresty-hmac:latest
    <<: *restart-policy
    network_mode: host
    volumes:
      - $NGINX_CONFIG_DIR:/etc/nginx/conf.d
      - $NGINX_CERTS_DIR:/ssl
