---
roles:
  - src: jnv.unattended-upgrades
    version: v1.8.0
  - src: weareinteractive.ufw
    version: 1.10.0
  - src: peaceman.docker
  - src: peaceman.elk
  - src: cloudalchemy.node-exporter
    version: 0.21.5

collections:
  - name: peaceman.shared_hosting
