---
roles:
  - src: jnv.unattended-upgrades
    version: v1.8.0
  - src: weareinteractive.ufw
    version: 1.10.0
  - src: geerlingguy.pip
    version: 2.0.0
  - src: geerlingguy.docker
    version: 2.8.2

collections:
  - name: peaceman.shared_hosting
